.TH "admin_t" 3 "18 Oct 2006" "Version 1.0" "Analyser-PX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <analyserpxTypes.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBinterval\fP"
.br
.ti -1c
.RI "int \fBhop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Adiministration Time type 
.PP
Definition at line 79 of file analyserpxTypes.h.
.SH "Member Data Documentation"
.PP 
.SS "int \fBadmin_t::hop\fP"
.PP
output name file administration. time bins counter 
.PP
Definition at line 81 of file analyserpxTypes.h.
.SS "int \fBadmin_t::interval\fP"
.PP
flow timeout.Time Bin definition 
.PP
Definition at line 80 of file analyserpxTypes.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Analyser-PX from the source code.
