.TH "hash_entry" 3 "18 Oct 2006" "Version 1.0" "Analyser-PX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hash_entry \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhash_entry\fP * \fBnext\fP"
.br
.ti -1c
.RI "const void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file hashtab.c.
.SH "Member Data Documentation"
.PP 
.SS "const void* \fBhash_entry::data\fP"
.PP
Actual entry we are storing. 
.PP
Definition at line 48 of file hashtab.c.
.SS "struct \fBhash_entry\fP* \fBhash_entry::next\fP"
.PP
Linked list buckets for collisions. 
.PP
Definition at line 47 of file hashtab.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for Analyser-PX from the source code.
